[features]
seeds = false
[programs.devnet]
myepicproject = "HwM4AQWCqLT6ixzpzw2Poz1GivsFjVWs68SPJe6hrf3E"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/allenchan/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
